services:
  app:
    container_name: charlotte_lan
    build: ./
    restart: always
    env_file: ./.env
    ports:
      - ${PORT}:8080
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=production
    stdin_open: true
    tty: true

