services:
  app:
    container_name: charlotte_lan
    build: ./
    restart: always
    env_file: ./.env
    ports:
      - ${PORT}:${PORT}
    environment:
      - DB_URI=${DB_URI}
      - NODE_ENV=production
    stdin_open: true
    tty: true

